http:
  port: ${http.port}

exchange.api:
  host: "exchange-api-0h7ap2.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  path: "api"

weather.api:
  host: "weather-api-0h7ap2.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  path: "api"

geocoding.api:
  host: "geocoding-api-0h7ap2.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  path: "api"

billing.api:
  host: "localhost"
  port: "8082"
  path: "api"
  
notification.api:
  host: "localhost"
  port: "8083"
  path: "api"